{{- range $cat, $catval := $.Values.catalogs }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "28"
  name: {{ $cat }}
  namespace: {{ $.Values.catalogNamespace }}
spec:
  image: {{ $.Values.registry }}/registry.redhat.io/redhat/{{ $cat }}:{{ $.Values.version }}
  sourceType: grpc
{{- end }}
