{{- range $key, $val := $.Values.catalogs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-26"
  name: oc-mirror-{{ $key }}
  namespace: {{ $.Values.namespace }}
spec:
  template:
    spec:
      serviceAccountName: oc-mirror
      containers:
      - name: container
        image: {{ $.Values.image }}
        command:
          - "/bin/sh"
          - "-c"
          - |
            cd /tmp
            # Download oc-mirror plugin
            wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/oc-mirror.tar.gz
            tar xvzf oc-mirror.tar.gz
            chmod +x
            # Run the mirroring process
            ./oc-mirror --config=/tmp/config/imagesetconfiguration.yaml docker://{{ $.Values.path }}/registry.redhat.io --dest-skip-tls=true
            # Rename the index image
            skopeo copy docker://{{ $.Values.path }}/{{ $.Values.catalog }} docker://{{ $.Values.path }}/registry.redhat.io/redhat/{{ $key }}:latest --tls-verify=false
        volumeMounts:
        - name: imageset-config
          mountPath: /tmp/config
        - name: docker-config
          mountPath: /root/.docker/
      restartPolicy: Never
      volumes:
      - name: imageset-config
        configMap:
          name: oc-mirror-{{ $key }}
      - name: docker-config
        secret:
          secretName: pull-secret
{{- end }}
