{{- range $cat, $catval := $.Values.catalogs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-29"
  name: oc-mirror-{{ $cat }}
  namespace: {{ $.Values.namespace }}
spec:
  template:
    spec:
      serviceAccountName: oc-mirror
      containers:
      - name: container
        image: {{ $.Values.jobImage }}
        command:
          - "/bin/sh"
          - "-c"
          - |
            cd /tmp
            # Download oc-mirror plugin
            wget {{ $.Values.ocMirror }}
            tar xvzf oc-mirror.tar.gz
            chmod +x oc-mirror
            # Run the mirroring process
            ./oc-mirror --config=/tmp/config/imagesetconfiguration.yaml docker://{{ $.Values.privateRegistry }} --dest-skip-tls=true
            # Rename the index image
            skopeo copy docker://{{ $.Values.privateRegistry }}/redhat/{{ $catval.catalog }} docker://{{ $.Values.privateRegistry }}/redhat/{{ $cat }}:{{ $.Values.version}} --tls-verify=false
        volumeMounts:
        - name: imageset-config
          mountPath: /tmp/config
        - name: docker-config
          mountPath: /root/.docker/
      restartPolicy: Never
      volumes:
      - name: imageset-config
        configMap:
          name: oc-mirror-{{ $cat }}
      - name: docker-config
        secret:
          secretName: pull-secret
{{- end }}
