{{ $wave := -24 }}
{{- range $cat, $catval := $.Values.catalogs }}
{{- range $pac, $pacval := $catval.packages }}

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "{{ $wave }}"
  name: {{ $pac }}
  namespace: {{ $pacval.namespace }}
spec:
  channel: {{ $pacval.channel }}
  installPlanApproval: Automatic
  name: {{ $pac }}
  source: {{ $cat }}
  sourceNamespace: {{ $.Values.catalogNamespace }}
{{ $wave := $wave add 1 }}
{{- end }}
{{- end }}
