namespace: oc-mirror
version: v4.14
image: registry.redhat.io/ubi9/skopeo:9.3-5
catalog: registry.redhat.io/redhat/redhat-operator-index:v4.12
registry: 



catalogs:

  servicemesh-v2-2-3:
    catalog: redhat-operator-index
    packages:
      servicemeshoperator:
        channel: stable
        version: 2.2.3-0
      kiali-ossm:
        channel: stable
        version: 1.57.7
      jaeger-product:
        channel: stable
        version: 1.47.1-5

  servicemesh-v2-4-4:
    catalog: redhat-operator-index
    packages:
      servicemeshoperator:
        channel: stable
        version: 2.4.4-0
      kiali-ossm:
        channel: stable
        version: 1.65.10
      jaeger-product:
        channel: stable
        version: 1.47.1-5

  oadp-v1-2-2:
    packages:
      redhat-oadp-operator:
        channel: stable-1.2
        version: 1.2.2

